<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Scopri di pi</name>
   <tag></tag>
   <elementGuidId>070331c4-d54e-4ad7-ae26-ccadc1eff5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/div[2]/div/div[1]/div/div[3]/div/div/div[1]/div/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>420a04a9-1552-4e3c-ba10-b4a009f7e6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BtnCta__button__w7eTRXBJ null BtnCta__bgtransparent__1n9xqjaE</value>
      <webElementGuid>ef7ca777-a4d1-4e1b-aa9a-851748783c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c42345f3-d4fa-450e-bdb3-0a1da6cf8934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-module-slug</name>
      <type>Main</type>
      <value>fuel-consumption-emission-focus-on</value>
      <webElementGuid>782d89b4-d4ab-4d52-8b5a-9b12a57b84b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-type</name>
      <type>Main</type>
      <value>OPEN_FOCUSON</value>
      <webElementGuid>3587cde4-3bc3-4381-899f-abb845b2ad4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Scopri di più</value>
      <webElementGuid>9786ab43-5df9-450f-9568-248a7feb1a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-focuson-type</name>
      <type>Main</type>
      <value>HorizontalSlider</value>
      <webElementGuid>0d6dc47c-2b83-4ab9-b127-41ecf77be6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scopri di più</value>
      <webElementGuid>e6ac0d43-fb8d-44e2-9593-8bf70b89ac12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;page-menu-hook DefaultPage__page__2K-llOv7&quot;]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[@class=&quot;Editorial__wrapper__1EtPDGax theme-ferrari-175&quot;]/div[@class=&quot;Editorial__row__2dfECJ3d&quot;]/div[@class=&quot;Container__container__1PqeYd8C Container__narrow__2CMB9CvO undefined Editorial__container__ajKH5vts&quot;]/div[@class=&quot;Editorial__text__N2aFczpm&quot;]/div[2]/button[@class=&quot;BtnCta__button__w7eTRXBJ null BtnCta__bgtransparent__1n9xqjaE&quot;]</value>
      <webElementGuid>8c535974-3818-4cee-8c02-675ec8117ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>3ed9fabc-9881-4477-acf3-a6e6b52344a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>51a32a4d-6c04-4a70-b8a1-92b75b92fcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMBINED: 17,3 l/100km'])[1]/following::button[1]</value>
      <webElementGuid>8073ff27-c84f-4385-92da-b77c030823b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTRA HIGH: 14,7 l/100km'])[1]/following::button[1]</value>
      <webElementGuid>702e1764-a38f-463a-af33-e2b1fc32eb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WLTP: Nuovi test per la certificazione dei consumi e delle emissioni di CO2'])[1]/preceding::button[1]</value>
      <webElementGuid>f3058761-9e2d-400b-ae30-acf33fe7f90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>45001524-195a-4e05-8bf5-b1a7af1f775b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Scopri di più' or . = 'Scopri di più')]</value>
      <webElementGuid>5c1bf2e0-0730-48da-922a-26105fc595f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
